### ISSUE TITLE
How to add fields to the partner skills plan spreadsheet without breaking it?

### ISSUE THREAD

**Issue by sayanghosh123** [tayganr/mcp-skills#1]
I came across this resource via our PTS and it is really awesome. The question is - can I add fields specific to our organisation at will without breaking the Power BI Desktop integration? The instructions in the template are very prescriptive and I didn't want to break it, but would be great to add a few columns here and there and don't really want to maintain two versions. Any feedback will be great!

**Comment by tayganr** [comment]
Hi @sayanghosh123, could you please give an example of the type of fields you are looking to add to the plan?

**Comment by sayanghosh123** [comment]
A few examples.

- "2. Competencies" and "5. Advanced Spec" I want to add a "Service Area" column that will map this to a service we offer to our clients.

- "4. Tracker" I want to add a "Service Area" column that will map this to a service we offer to our clients. I also want to add a column for the related competency names.

The are a few others but of the same nature. Will those break the PBIX integration and if so, is the fix a simple schema refresh inside Power BI Desktop?

**Comment by tayganr** [comment]
@sayanghosh123 - Adding additional fields to the excel spreadsheet should not break the Power BI template. As you have mentioned, you will need to refresh the PBIX schema to make these fields available in the report.

**Example:**
1. Download the latest template files - XLSX and PBIT (these have recently been updated to include the latest exams, certifications, and advanced specialisations).
2. Update the Excel spreadsheet to include the additional fields.
3. Open the Power BI Template, point it to the path of the updated spreadsheet.
4. Update the data model of the Power BI report to include the additional fields. 
5. (Optional) Export the Power BI report as a new reusable template.

**Comment by sayanghosh123** [comment]
Thanks, that is appreciated!
